$ScriptInfo = @"
================================================================================
MRS_Explorer.ps1 | v1.3
by Roman Zarka
================================================================================
SAMPLE SCRIPT IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND.
"@

Function OnApplicationLoad {
	If (Test-Path .\MRS_Explorer.cfg) {
		Write-Console "INFO: Preference file detected."
		$script:Config = Import-Csv ".\MRS_Explorer.cfg" }
	Return $true
}

Function OnApplicationExit {
	If ($SaveConfig -eq $true) {
		$ConfigConnection = $comboConnection.Text
		$ConfigConnectionUrl = $textConnectionUrl.Text
		$ConfigUserName = $MRS_ExplorerRemoteCredentials.UserName
		$ConfigPassword = $MRS_ExplorerRemoteCredentials.Password | ConvertFrom-SecureString
		"Connection,ConnectionUrl,UserName,Password" | Out-File "c:\Scripts\MRS_Explorer.cfg"
		"$ConfigConnection,$ConfigConnectionUrl,$ConfigUserName,$ConfigPassword" | Out-File "c:\Scripts\MRS_Explorer.cfg" -Append }
	If ($MRS_ExplorerRemoteSession -ne $null) {
		Write-Console "INFO: Disconnect remote session."
		Remove-PSSession $MRS_ExplorerRemoteSession }
	$script:ExitCode = 0
}

Function Call-MRS_Explorer {
	[void][reflection.assembly]::LoadWithPartialName("System.Windows.Forms")
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formMRSExplorer = New-Object 'System.Windows.Forms.Form'
	$tabContainer = New-Object 'System.Windows.Forms.TabControl'
	$tabXml = New-Object 'System.Windows.Forms.TabPage'
	$splitVertical = New-Object 'System.Windows.Forms.SplitContainer'
	$textNodePath = New-Object 'System.Windows.Forms.TextBox'
	$buttonImport = New-Object 'System.Windows.Forms.Button'
	$textImportFile = New-Object 'System.Windows.Forms.TextBox'
	$tabQuery = New-Object 'System.Windows.Forms.TabPage'
	$buttonReset = New-Object 'System.Windows.Forms.Button'
	$checkboxSavePreferences = New-Object 'System.Windows.Forms.CheckBox'
	$buttonConnect = New-Object 'System.Windows.Forms.Button'
	$buttonSearch = New-Object 'System.Windows.Forms.Button'
	$textSearch = New-Object 'System.Windows.Forms.TextBox'
	$buttonExportXML = New-Object 'System.Windows.Forms.Button'
	$textConnectionUrl = New-Object 'System.Windows.Forms.TextBox'
	$comboConnection = New-Object 'System.Windows.Forms.ComboBox'
	$panelQueryStatus = New-Object 'System.Windows.Forms.Panel'
	$textQueryStatus = New-Object 'System.Windows.Forms.TextBox'
	$buttonBrowseXML = New-Object 'System.Windows.Forms.Button'
	$buttonRefresh = New-Object 'System.Windows.Forms.Button'
	$comboFilter = New-Object 'System.Windows.Forms.ComboBox'
	$dataMoveRequest = New-Object 'System.Windows.Forms.DataGridView'
	$labelSessionStatus = New-Object 'System.Windows.Forms.Label'
	$treeCollectionNodes = New-Object 'System.Windows.Forms.TreeView'
	$listCollectionEntries = New-Object 'System.Windows.Forms.ListBox'
	$fileOpenDialog = New-Object 'System.Windows.Forms.OpenFileDialog'
	$menuContext = New-Object 'System.Windows.Forms.ContextMenuStrip'
	$menuContextCopy = New-Object 'System.Windows.Forms.ToolStripMenuItem'
	$textEntryDetails = New-Object 'System.Windows.Forms.TextBox'
	$splitHorizontal = New-Object 'System.Windows.Forms.SplitContainer'
	$fileSaveDialog = New-Object 'System.Windows.Forms.SaveFileDialog'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	
	Function Write-Console ($LogString) {
	    $LogStatus = $LogString.Split(":")[0]
	    If ($LogStatus -eq "ALERT") { Write-Host "`n$LogString" -ForegroundColor Yellow }
	    If ($LogStatus -eq "INFO") { Write-Host "`n$LogString" -ForegroundColor Cyan }
	    If ($LogStatus -eq "ERROR") { Write-Host "`n$LogString" -BackgroundColor Red }
	    If ($LogStatus -eq "SUCCESS") { Write-Host "`n$LogString" -ForegroundColor Green }
	    If ($LogStatus -eq "DEBUG") { Write-Host "`n$LogString" -ForegroundColor Gray }
	    If ($LogStatus -eq "") { Write-Host "`n" }
	}
	
	Function Load-DataGridView ($DataGridView, $Item, $DataMember) {
		$DataGridView.SuspendLayout()
		$DataGridView.DataMember = $DataMember
		If ($Item -Is [System.ComponentModel.IListSource] -Or $Item -Is [System.ComponentModel.IBindingList] -Or $Item -Is [System.ComponentModel.IBindingListView] ) { $DataGridView.DataSource = $Item }
		Else {
			$Array = New-Object System.Collections.ArrayList
			If ($Item -is [System.Collections.IList]) { $Array.AddRange($Item) }
			Else { $Array.Add($Item) }
			$DataGridView.DataSource = $Array }
		$DataGridView.ResumeLayout()
	}
	
	Function Retrieve-MoveRequests {
        Write-Console "INFO: Retrieve move requests..."
		$panelQueryStatus.Show()
		$dataMoveRequest.DataSource = $null
		If ($textSearch.Text -ne "" -and $textSearch.Text -ne "Name, Alias, or Batch") {
			If ($comboFilter.Text -eq "All") { $MoveRequestList = (Get-MoveRequest -ResultSize Unlimited | Where { $_.Alias -like "*$($textSearch.Text)*" -or $_.Name -like "*$($textSearch.Text)*" -or $_.BatchName -like "*$($textSearch.Text)*" } | Select Name,Alias,BatchName,RemoteHostName,Flags,TargetDatabase,Status) | Sort Alias }
			Else { $MoveRequestList = (Get-MoveRequest -ResultSize Unlimited -MoveStatus "$($comboFilter.Text)" | Where { $_.Alias -like "*$($textSearch.Text)*" -or $_.Name -like "*$($textSearch.Text)*" -or $_.BatchName -like "*$($textSearch.Text)*" } | Select Name,Alias,BatchName,RemoteHostName,Flags,TargetDatabase,Status) | Sort Alias } }
		Else { 
			If ($comboFilter.Text -eq "All") { $MoveRequestList = (Get-MoveRequest -ResultSize Unlimited | Select Name,Alias,BatchName,RemoteHostName,Flags,TargetDatabase,Status) | Sort Alias }
			Else { $MoveRequestList = (Get-MoveRequest -ResultSize Unlimited -MoveStatus "$($comboFilter.Text)" | Select Name,Alias,BatchName,RemoteHostName,Flags,TargetDatabase,Status) | Sort Alias } }
		$panelQueryStatus.Hide()
		If ($MoveRequestList -eq $null) {
			Write-Console "ERROR: No move request results found."
			$buttonBrowseXML.Enabled = $false; $buttonExportXML.Enabled = $false }
		Else {
		    Load-DataGridView $dataMoveRequest $MoveRequestList
			$buttonBrowseXML.Enabled = $true; $buttonExportXML.Enabled = $true }
	}
	
	Function Retrieve-MoveRequestStatistics {
        Write-Console "INFO: Retrive move request report..."
		$panelQueryStatus.Show()
		$textEntryDetails.Clear(); $listCollectionEntries.Items.Clear(); $treeCollectionNodes.Nodes.Clear()
		$textImportFile.Text = $dataMoveRequest.CurrentRow.Cells["Alias"].Value
		$script:MoveRequest = (Get-MoveRequestStatistics $textImportFile.Text -IncludeReport)
		$panelQueryStatus.Hide()
		ForEach ($Collection in ($MoveRequest | Get-Member | Where { $_.MemberType -eq "Property" -and $_.Name -ne "Length" })) { $treeCollectionNodes.Nodes.Add($Collection.Name) }
	}
	
	$buttonImport_Click={
		$fileOpenDialog.Reset()
		$fileOpenDialog.Title = "Open Move Request XML Export File"
		$fileOpenDialog.ShowDialog()
		$textImportFile.Text = $fileOpenDialog.FileName
		$textEntryDetails.Clear(); $listCollectionEntries.Items.Clear(); $treeCollectionNodes.Nodes.Clear()
		$script:MoveRequest = Import-Clixml $fileOpenDialog.FileName
		ForEach ($Collection in ($MoveRequest | Get-Member | Where { $_.MemberType -eq "Property" -and $_.Name -ne "Length" })) { $treeCollectionNodes.Nodes.Add($Collection.Name) }
	}
	
	$treeCollectionNodes_AfterSelect=[System.Windows.Forms.TreeViewEventHandler]{
		$script:SelectedTreeNodePath = $treeCollectionNodes.SelectedNode.FullPath.Replace("\",".")
		$textNodePath.Text = $SelectedTreeNodePath
		$textEntryDetails.Clear(); $listCollectionEntries.Items.Clear()
		$Expression = '$MoveRequest' + ".$SelectedTreeNodePath"
		$Entries = Invoke-Expression $Expression
		If ($Entries.Count -eq $null) {
			[string]$Entry = Invoke-Expression $Expression
			$Entries = $Entry.Split(";").Trim() }
		Foreach ($Item in $Entries) { $listCollectionEntries.Items.Add($Item) }
		$SelectedTreeNode = $treeCollectionNodes.SelectedNode
		$SelectedTreeNode.Nodes.Clear()
		If ($textNodePath.Text -eq "Report") {
			$Expression = '$MoveRequest' + ".$SelectedTreeNodePath" + ' | Get-Member | Where { $_.MemberType -eq "Property" -and $_.Name -ne "Length" }'
			$Collection = Invoke-Expression $Expression
			If ($Collection -ne $null) { ForEach ($Item in $Collection) { $SelectedTreeNode.Nodes.Add($Item.Name) } } }
	}
	
	$listCollectionEntries_SelectedIndexChanged={
		$textEntryDetails.Clear()
		If ($listCollectionEntries.Items.Count -gt 1) { $textNodePath.Text = $SelectedTreeNodePath + "[" + $listCollectionEntries.SelectedIndex + "]" }
		$Expression = '$MoveRequest' + ".$($textNodePath.Text)" + ' | Out-String'
		$Entries = Invoke-Expression $Expression
		If ($Entries -ne $null) { ForEach ($Item in $Entries) { $textEntryDetails.Text = $Item } }
	}
	
	$menuContextCopy_Click={
		$listCollectionEntries.SelectedItem | Clip
	}
	
	$tabQuery_Enter={
		If ($MRS_ExplorerRemoteSession -eq $null -and $LocalSession -ne "Initialized") {
			$CheckLocalSession = (Get-PSSession)
				If ($CheckLocalSession.State -eq "Opened" -and $CheckLocalSession.ConfigurationName -eq "Microsoft.Exchange" -and $CheckLocalSession.Availability -eq "Available") {
					Write-Console "ALERT: Local session detected."; $script:LocalSession = "Initialized"
					$labelSessionStatus.Text = "Connected"; $labelSessionStatus.BackColor = 'Green'; $buttonConnect.Text = "Disconnect"
					$comboConnection.Enabled = $false; $textConnectionUrl.Text = "$($CheckLocalSession.ComputerName)"
                    Retrieve-MoveRequests } }
	}
	
	$comboConnection_SelectedIndexChanged={
		If ($comboConnection.Text -eq "Commercial Worldwide") { $textConnectionUrl.Text = "https://outlook.office365.com/powershell-liveid" }
		If ($comboConnection.Text -eq "Federal & Defense ITAR") { $textConnectionUrl.Text = "https://outlook.office365.us/powershell-liveid" }
		If ($comboConnection.Text -eq "On-Premises & Dedicated") { $textConnectionUrl.Text = "Enter a custom PowerShell endpoint..." }
	}
	
	$buttonConnect_Click={
		If ($buttonConnect.Text -eq "Connect") { $ConnectionStatus = "Disconnected" }
		If ($buttonConnect.Text -eq "Disconnect") { $ConnectionStatus = "Connected" }
		If ($ConnectionStatus -eq "Disconnected") {
            Write-Console "INFO: Connecting to remote PowerShell session..."
			$buttonConnect.Text = "Connecting..."; $labelSessionStatus.Text = ""; $labelSessionStatus.BackColor = 'Transparent'
			If ($comboConnection.Text -eq "On-Premises & Dedicated") {
				Write-Console "INFO: Trying Kerberos authentication..."
				$script:MRS_ExplorerRemoteSession = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri $textConnectionUrl.Text -Authentication Kerberos -AllowRedirection }
			If ($MRS_ExplorerRemoteSession -eq $null -and $Config.UserName -ne $null -and $Config.Password -ne $null) {
					Write-Console "INFO: Trying preference credentials..."
					$MRS_ExplorerRemoteCredentials = New-Object System.Management.Automation.PSCredentials($Config.UserName, $Config.Password)
					$script:MRS_ExplorerRemoteSession = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri $textConnectionUrl.Text -Authentication Basic -Credential $MRS_ExplorerRemoteCredentials -AllowRedirection }
			If ($MRS_ExplorerRemoteSession -eq $null) {
				Write-Console "ALERT: Prompting for credentials..."
				Try { $script:MRS_ExplorerRemoteCredentials = Get-Credential }
				Catch { Write-Console "ERROR: Credential prompt failed." }
				If ($MRS_ExplorerRemoteCredentials -ne $null) { $script:MRS_ExplorerRemoteSession = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri $textConnectionUrl.Text -Authentication Basic -Credential $MRS_ExplorerRemoteCredentials -AllowRedirection } }
			If ($MRS_ExplorerRemoteSession -ne $null) {
				Write-Console "SUCCESS: Remote session connected."
				Import-Module (Import-PSSession $MRS_ExplorerRemoteSession -DisableNameChecking -AllowClobber) -Global -DisableNameChecking
				$labelSessionStatus.Text = "Connnected"; $labelSessionStatus.BackColor = 'Green'; $buttonConnect.Text = "Disconnect"
				Retrieve-MoveRequests }
			If ($MRS_ExplorerRemoteSession -eq $null) {
				Write-Console "ERROR: Remote connection failed."
				$buttonConnect.Text = "Connect"; $labelSessionStatus.Text = "Offline"; $labelSessionStatus.BackColor = 'Red'
				$MRS_ExplorerRemoteCredentials = $null; $MRS_ExplorerRemoteSession = $null } }
		If ($ConnectionStatus -eq "Connected") {
			$dataMoveRequest.DataSource = $null; $textSearch.Text = ""; $comboFilter = "All"
			Get-PSSession | Remove-PSSession
            $script:MRS_ExplorerRemoteSession = $null; $script:MRS_ExplorerRemoteCredentials = $null 
			$comboConnection.Enabled = $true; $labelSessionStatus.Text = "Offline"; $labelSessionStatus.BackColor = "Red"; $buttonConnect.Text = "Connect"
			Write-Console "SUCCESS: Remote session disconnected." }
	}
	
	$textConnectionUrl_Enter={
		If ($comboConnection.Text -eq "On-Premises & Dedicated" -and $textConnectionUrl.Text -eq "Enter a custom Powershell endpoint...") { $textConnectionUrl.Text = "" }
	}
	
	$checkboxSavePreferences_CheckedChanged={
		If ($checkboxSavePreferences.Checked) { $script:SaveConfig = $true }
	}
	
	$buttonBrowseXML_Click={
		Retrieve-MoveRequestStatistics
		$tabContainer.SelectedTab = $tabXml
	}
	
	$dataMoveRequest_DoubleClick={
		Retrieve-MoveRequestStatistics
		$tabContainer.SelectedTab = $tabXml
	}
	
	$buttonExportXML_Click={
		$fileSaveDialog.Reset()
		$fileSaveDialog.Title = "Save Move Request XML Export File"
		$fileSaveDialog.FileName = "$($dataMoveRequest.CurrentRow.Cells["Alias"].Value).xml"
		$fileSaveDialog.ShowDialog()
		Retrieve-MoveRequestStatistics
		$MoveRequest | Export-Clixml $fileSaveDialog.FileName
	}
	
	$comboFilter_SelectedIndexChanged={
        Retrieve-MoveRequests
	}
	
	$buttonRefresh_Click={
        Retrieve-MoveRequests
	}
	
	$textSearch_Enter={
		If ($textSearch.Text -eq "Name, Alias, or Batch") { $textSearch.Text = "" }
	}
	
	$buttonSearch_Click={
        Retrieve-MoveRequests
	}
	
	$buttonReset_Click={
		$textSearch.Text = "Name, Alias, or Batch"
        If ($comboFilter.Text -eq "All") { &$comboFilter_SelectedIndexChanged }
        Else { $comboFilter.Text = "All" }
	}
	
	$Form_StateCorrection_Load={
		$formMRSExplorer.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed={
		Try {
			$buttonImport.remove_Click($buttonImport_Click)
			$buttonReset.remove_Click($buttonReset_Click)
			$checkboxSavePreferences.remove_CheckedChanged($checkboxSavePreferences_CheckedChanged)
			$buttonConnect.remove_Click($buttonConnect_Click)
			$buttonSearch.remove_Click($buttonSearch_Click)
			$textSearch.remove_Enter($textSearch_Enter)
			$buttonExportXML.remove_Click($buttonExportXML_Click)
			$textConnectionUrl.remove_Enter($textConnectionUrl_Enter)
			$comboConnection.remove_SelectedIndexChanged($comboConnection_SelectedIndexChanged)
			$buttonBrowseXML.remove_Click($buttonBrowseXML_Click)
			$buttonRefresh.remove_Click($buttonRefresh_Click)
			$comboFilter.remove_SelectedIndexChanged($comboFilter_SelectedIndexChanged)
			$dataMoveRequest.remove_DoubleClick($dataMoveRequest_DoubleClick)
			$tabQuery.remove_Enter($tabQuery_Enter)
			$treeCollectionNodes.remove_AfterSelect($treeCollectionNodes_AfterSelect)
			$listCollectionEntries.remove_SelectedIndexChanged($listCollectionEntries_SelectedIndexChanged)
			$menuContextCopy.remove_Click($menuContextCopy_Click)
			$formMRSExplorer.remove_Load($Form_StateCorrection_Load)
			$formMRSExplorer.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		Catch [Exception]{ }
	}

	$formMRSExplorer.Controls.Add($tabContainer)
	$formMRSExplorer.ClientSize = '884, 461'
	$formMRSExplorer.Name = "formMRSExplorer"
	$formMRSExplorer.StartPosition = 'CenterScreen'
	$formMRSExplorer.Text = "MRS Explorer v1.3"
	$formMRSExplorer.Icon = [System.Convert]::FromBase64String('
AAABAAUAAAAAAAEAIABoCAAAVgAAADAwAAABACAAqCUAAL4IAAAgIAAAAQAgAKgQAABmLgAAGBgA
AAEAIACICQAADj8AABAQAAABACAAaAQAAJZIAACJUE5HDQoaCgAAAA1JSERSAAABAAAAAQAIBgAA
AFxyqGYAAAgvSURBVHic7d3BcdzmGcfhvzMuQJe9ZpQKIl/35FQgVhArFaiHdOAKIqUBU27AsA97
NZMGjMl1D+GkAeeA3VlRpmguCSzw4X2eGQ/HHpn6LvjhxYePywQAAAAAAAAAAAAAAAAAAFioL+Ze
AOu13+ZVkrdJrpK8SHKd5Mck15td+hmXxoEAMKr9Ni8zXPBvk7x84I/2OQRhs8v15AvjXgLAKPbb
vEnyOsPFf67bJF2SD0k608HlCABPds+IP5abDEF4v9nlZsTvyycEgLOcMeKP5TZ39w5uL/B3liEA
PMozR/wx3ST5Psl3poPnEwA+a8IRfyx97u4dmA7OJADcMcOIP6YuQwy8ZnwkASDJokb8sfTxmvF3
CUBhDYz4Y7qO14y/IQDFND7ij+X4mvHDZpdu3qXMSwCKWOGIP5aPDyGVe80oACtWbMQfS6nXjAKw
Mkb8UR0PIa32NaMArIQR/yK6nGKwiulAABpmxJ9Vn9NGYrOvGQWgMUb8xWrysw4EoBFG/Kb0Oewd
LP01owAs2GHE/ybJmxjxW7XozzoQgIXZb/MiwwX/TZJX866GCdxsdvlq7kUcfTn3Ahjst7nKcNEb
8ddtUVEXgBkZ8ZmbAFyYEZ8lEYALMeKzRAIwISM+SycAIzPi0xIBGIkRnxYJwDMY8WmdAJzJiM+a
CMAjGfFZIwF4gBGftROATxjxqUQADoz4VFQ6AEZ8qisXACM+nJQJgBF/Vl2Sr2deA/dYdQAOn593
/NDMl7MuppYuyU9Jfjh+JNZ+m1/nXBD3W10ADiP+8UMzjfjTO37k1Y9Z0cdlV7GaABxG/NcZnu+Z
Tp/hgv9XXPDNazoARvyL6HP3Dt/PuRjG1VwAjPiTO/7m3OMFv7pfh8VJMwEw4k+my7Bh93Nc8OUs
OgBG/El0+WSHnroWFwAj/qjs0POgxQTAiD+KPnboOcMiArDf5pcY8Z+ijx16nmERAYiL/7Hs0DOq
pQSA+3WxQ8+EBGBZutih54IEYD526JmdAFxOHzv0LIwATKePHXoWTgDGY4ee5gjA03WxQ0/jBODx
utihZ2UE4JE2u/xl7jXA2P4w9wKA+QgAFCYAUJgAQGECAIUJABQmAFCYAEBhAgCFCQAUJgBQmABA
YQIAhQkAFCYAUJgAQGECAIUJABQmAFCYAEBhAgCFCQAUJgBQmABAYQIAhQkAFCYAUJgAQGECAIUJ
ABQmAFCYAEBhAgCFCQAUJgBQmABAYQIAhQkAFCYAUJgAQGECAIUJABQmAFCYAEBhAgCFCQAUJgBQ
mABAYQIAhQkAFCYAUJgAQGECAIUJABQmAFCYAEBhAgCFCQAUJgBQmABAYQIAhQkAFCYAUJgAQGEC
AIUJABQmAFCYAEBhAgCFCQAUJgBQmABAYQIAhQkAFCYAUJgAQGECAIUJABQmAFCYAEBhAgCFCQAU
JgBQmABAYQIAhQkAFCYAUJgAQGECAIUJABQmAFCYAEBhAgCFCQAUJgBQmABAYQIAhQkAFCYAUJgA
QGECAIUJABQmAFCYAEBhAgCFCQAUJgBQmABAYQIAhX059wIa0CV5P/ciYAoCcL/bJO+SfLvZpZ93
KTAdAbirS/J+s8u7mdcBFyEA7vYUVjkA10k+uNtTWbUA9En+meQf7vZQJwDXGZ7tr+deCCzJmgPQ
x90eHrTGALjbwyOtJQB9km+TXLvbw+O1HoB3Ge723czrgCa1GIA+w93+3WaX25nXAk1rKQDv4m4P
o1p6AG4y/CCOuz1MYIkBuM2wk//tZpebuRcDa7akANzktJPvbg8XsJQA/D3JH5P8Ocmf9tv8kCSe
92FaX8y9gI/tt7lK8jrJm4/+822G6aBP8p8kPye5FYe27Lf5de41LMVmt5zrbjEL+dh+mxdJrpJ8
k+Tr3/njXYZI/DvJLxlCceMxYlkE4EQAzrDf5mWSvyX5a5KXZ/7v3eHrT0n+m8Mk4bTg5QnAiQA8
0X6brzNMBVdJXjzz291kmBx+Ovz7DxkeLbx5mIAAnAjACPbbvMmwX3A1wbfvD//cJPlfYlPyuQTg
RABGdHhEuEryNuc/IjyFTcknEIATAZjIfptXGR4R3uT5jwhP1cWm5G8IwIkAXMDhleJxv2ApusPX
cpuSAnAiABd0eKX4JkMMXs27mgetelNSAE4EYCaH/YK3GaaCl7Mu5jx9Gt+UFIATAViAz5w6bFET
m5ICcCIAC3LmqcMWdVnApqQAnAjAQj3z1GGLusPXyTclBeBEABow8qnDFo26KSkAJwLQmIlPHbao
z5mbkgJwIgCNmuHUYYvu3ZTMIRIIwCos5NQhDRKAlVnoqUMWSgBWqqFTh8xIAApo+NQhExOAYlZ0
6pARCEBRBU4d8ggCQMVThxwIAHc4dViLAPBZTh2u3s1ml6/mXsSRACyUU4ercZvhh64+JOmW9ulP
AtAApw6b02f4Bbcflva5DJ8SgMY4dbhY10l+zPDLbfuZ1/JoAtAopw5n1+cw2m92uZ53KU8nACvg
1OHFdDk9y6/iw1oFYGWcOhzVbQ7P8hku+tX9bgcBWCmnDp/sJsn3Sb5by13+IQJQgFOHD/r4Nd31
Gu/yDxGAYpw6TDLc5bs08JpuagJQWLFTh02+ppuaALDWU4d9Dhd9y6/ppiYA3NH4qcMup2f5ft6l
tEEA+KwGTh32uftuvtQG3hgEgN+1sFOHpV7TTU0AOMsMpw6Ph3GOG3ju8iMSAJ5swlOHx9d0793l
pyUAPNsIpw4X/TPzayYAjOqMU4d9vKabnQAwmXtOHTqMAwAAAAAAAAAAAAAAAAAA8Dj/BwUilE3t
w/o7AAAAAElFTkSuQmCCKAAAADAAAABgAAAAAQAgAAAAAACAJQAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuoWADrrDgAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOeoMADnrVgA6
67UAOuv7ADrr+QA6670AOutyADrrKgA66wIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
OuoCADrrOgA56pkAOurrADnq/wA56/8AOer/ADnq/wA56/8AOer/ADnq/wA669sAOuuVADrqSgA6
6wwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAADnqIAA663wAOuvZADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8A
Ouv/ADrr/wA66/8AOuv/ADrr/wA66vMAOuu1ADnqagA66yAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAADnrEAA56mAAOeq/ADrr/QA56v8AOuv/ADrr/wA66/8AOuv/
ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8A
OuvVADrrRgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADnqBAA660QAOuujADnq8QA56v8AOuv/ADnq
/wA56v8AOuv/ADnq/wA56/8AOer/ADnq/wA56/8AOer/ADnq/wA56/8AOer/ADnq/wA56/8AOer/
ADnq/wA56/8AOer/ADnq/wA56/8AOer/ADrrcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA56igAOuuHADrr3wA6
6/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv3ADrr1QA667MAOeqPADnqagA660gAOepCADrr
/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADnqcAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA66xQA
OutqADnrxwA56v8AOuv/ADrr+wA66+0AOuvPADrrqwA664cAOutkADrrQAA66xwAOuoCAAAAAAAA
AAAAAAAAAAAAAAAAAAAAOuogADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr
/wA66/8AOuv/ADnqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAA66wgAOutKADnrkwA56r0AOuujADrrgQA661wAOus4ADrrGgA56wQAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuogADnq/wA56/8AOer/ADnq/wA5
6/8AOer/ADnq/wA56/8AOer/ADnq/wA56/8AOer/ADrrcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA56p8AOepgADnrCAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
OuogADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADnqcAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6688AOuv/ADrr
5QA664MAOusiADrrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAOuogADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8A
Ouv/ADrr/wA66/8AOuv/ADnqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA56s8AOuv/ADnq/wA56v8AOuv7ADrruQA661IAOusIAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuogADnq/wA56/8AOer/
ADnq/wA56/8AOer/ADnq/wA56/8AOer/ADnq/wA56/8AOer/ADrrcAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6688AOuv/ADrr/wA66/8AOuv/ADrr/wA6
6/8AOuvNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAOuogADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/
ADnqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6688A
Ouv/ADrr/wA66/8AOuv/ADrr/wA56v8AOuvfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuogADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr
/wA66/8AOuv/ADrr/wA66/8AOuv/ADnqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA56s8AOuv/ADnq/wA56v8AOuv/ADnq/wA56v8AOerfAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuogADnq/wA5
6/8AOer/ADnq/wA56/8AOer/ADnq/wA56/8AOer/ADnq/wA56/8AOer/ADrrcAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6688AOuv/ADrr/wA66/8AOuv/
ADrr/wA66/8AOuvfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAOuogADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA6
6/8AOuv/ADnqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAA6688AOuv/ADrr/wA66/8AOuv/ADrr/wA56v8AOuvfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuogADrr/wA66/8AOuv/ADrr/wA66/8A
Ouv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADnqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA56s8AOuv/ADnq/wA56v8AOuv/ADnq/wA56v8AOerfAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuog
ADnq/wA56/8AOer/ADnq/wA56/8AOer/ADnq/wA56/8AOer/ADnq/wA56/8AOer/ADrrcAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6688AOuv/ADrr/wA6
6/8AOuv/ADrr/wA66/8AOuvfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAOuogADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/
ADrr/wA66/8AOuv/ADnqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA6688AOuv/ADrr/wA66/8AOuv/ADrr/wA56v8AOuvfAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuogADrr/wA66/8AOuv/ADrr
/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADnqcAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA56s8AOuv/ADnq/wA56v8AOuv/ADnq/wA56v8A
OerfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAOuogADnq/wA56/8AOer/ADnq/wA56/8AOer/ADnq/wA56/8AOer/ADnq/wA56/8AOer/ADrr
cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6688AOuv/
ADrr/wA66/8AOuv/ADrr/wA66/8AOuvfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuogADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA6
6/8AOuv/ADrr/wA66/8AOuv/ADnqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA6688AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuvfAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOeogADrr/wA66/8A
Oev/ADrr/wA66/8AOev/ADrr/wA66/8AOev/ADrr/wA66/8AOev/ADrqcAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6688AOuv/ADrr/wA56/8AOuv/ADrr
/wA66/8AOuvfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAOusgADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8A
Ouv/ADnqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6
688AOuv/ADrr/wA66/8AOuv/ADrr/wA56v8AOerfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOeogADrq/wA66v8AOuv/ADrq/wA66v8AOuv/
ADrq/wA66v8AOuv/ADrq/wA66v8AOuv/ADnqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA6688AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuvfAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOeogADrr
/wA66/8AOev/ADrr/wA66/8AOev/ADrr/wA66/8AOev/ADrr/wA66/8AOev/ADrqcAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6688AOuv/ADrr/wA56/8A
Ouv/ADrr/wA66/8AOuvfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAOusgADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr
/wA66/8AOuv/ADnqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAA6688AOuv/ADrr/wA66/8AOuv/ADrr/wA56v8AOerfAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOeogADrq/wA66v8AOuv/ADrq/wA6
6v8AOuv/ADrq/wA66v8AOuv/ADrq/wA66v8AOuv/ADnqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6688AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuvf
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
OeogADrr/wA66/8AOev/ADrr/wA66/8AOev/ADrr/wA66/8AOev/ADrr/wA66/8AOev/ADrqcAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6688AOuv/ADrr
/wA56/8AOuv/ADrr/wA66/8AOuvfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAOusgADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8A
Ouv/ADrr/wA66/8AOuv/ADnqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA6688AOuv/ADrr/wA66/8AOuv/ADrr/wA56v8AOerfAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOeogADrq/wA66v8AOuv/
ADrq/wA66v8AOuv/ADrq/wA66v8AOuv/ADrq/wA66v8AOuv/ADnqcAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6688AOuv/ADrr/wA66/8AOuv/ADrr/wA6
6/8AOuvfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAOeogADrr/wA66/8AOev/ADrr/wA66/8AOev/ADrr/wA66/8AOev/ADrr/wA66/8AOev/
ADrqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6688A
Ouv/ADrr/wA56/8AOuv/ADrr/wA66/8AOuvjADnqBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOusgADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr
/wA66/8AOuv/ADrr/wA66/8AOuv/ADnqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA6688AOuv/ADrr/wA66/8AOuv/ADrr/wA56v8AOuv/ADrq6wA56rUA
Oup2ADrrOgA66wYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOeogADrq/wA6
6v8AOuv/ADrq/wA66v8AOuv/ADrq/wA66v8AOuv/ADrq/wA66v8AOuv/ADnqcAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6668AOuv9ADrr/wA66/8AOuv/
ADrr/wA66/8AOev/ADrr/wA66/8AOev/ADrr/wA66/cAOeu/ADrrgQA56kQAOusQADrqAAAAAAAA
AAAAAAAAAAAAAAAAOeogADrr/wA66/8AOev/ADrr/wA66/8AOev/ADrr/wA66/8AOev/ADrr/wA6
6/8AOev/ADrqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAA56gIAOeoyADrrjwA66+cAOuv/ADnq/wA56/8AOev/ADnr/wA56/8AOev/ADnr/wA56/8AOev/
ADnr/wA56/8AOuv3ADrryQA664sAOutOADrrFgAAAAAAOusgADrr/wA66/8AOuv/ADrr/wA66/8A
Ouv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrrcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA66wgAOepQADrrsQA66/sAOuv/ADrr
/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr+QA56tMAOuun
ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrrcAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA66xYAOutyADrrzwA66v0AOev/ADrr/wA66/8AOev/ADrr/wA66/8AOev/ADrr
/wA66/8AOev/ADrr/wA66/8AOev/ADrr/wA66/8AOev/ADrr/wA66/8AOev/ADrr/wA66/8AOev/
ADrr/wA66/8AOev/ADrqcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrrAgA66zQAOuuRADrr6QA5
6/8AOev/ADnr/wA56/8AOev/ADnr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr
/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrrcAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAADrrCAA66lIAOuuxADrr+wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA6
6/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOerVADrr
RgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrqGAA663QA
OuvRADrq/QA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA6
6/MAOuu1ADrqagA66yAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAOusCADnqNAA665MAOuvpADrr/wA56/8AOev/ADrr/wA56/8A
Oev/ADrr/wA56tsAOuuVADnqSgA66wwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOeoK
ADrrUgA667MAOuv7ADrr+QA6670AOetyADrrKgA56gIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuoWADrrDgAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///////wAA////////AAD////z
//8AAP///4A//wAA///8AAf/AAD///AAAP8AAP//gAAAPwAA//wAAAA/AAD/8AAAAD8AAP+AAfAA
PwAA/AD/8AA/AAD8f//wAD8AAPwf//AAPwAA/AP/8AA/AAD8A//wAD8AAPwD//AAPwAA/AP/8AA/
AAD8A//wAD8AAPwD//AAPwAA/AP/8AA/AAD8A//wAD8AAPwD//AAPwAA/AP/8AA/AAD8A//wAD8A
APwD//AAPwAA/AP/8AA/AAD8A//wAD8AAPwD//AAPwAA/AP/8AA/AAD8A//wAD8AAPwD//AAPwAA
/AP/8AA/AAD8A//wAD8AAPwD//AAPwAA/AH/8AA/AAD8AB/wAD8AAPwAAfAAPwAA/AAAEAA/AAD/
gAAAAD8AAP/wAAAAPwAA//wAAAA/AAD//4AAAD8AAP//8AAA/wAA///8AAf/AAD///+AP/8AAP//
//P//wAA////////AAD///////8AACgAAAAgAAAAQAAAAAEAIAAAAAAAgBAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA66wAAOusQAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA66yIAOut+ADrr3QA66/0A
OuvHADrrfAA66zIAOusCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrrDgA662IAOuvBADrr
/QA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66+cAOuudADrrUgA66w4AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOusCADrrRgA666UA
Ouv1ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr+QA6
634AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOusqADrr
iQA66+UAOuv/ADrr/wA66/8AOuv/ADrr6QA668UAOuujADrrfgA669kAOuv/ADrr/wA66/8AOuv/
ADrr/wA66/8AOuv/ADrrnwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA66xQA
OutsADrryQA66+EAOuu/ADrrmwA663gAOutUADrrMAA66w4AAAAAAAAAAAAAAAAAAAAAADrrvwA6
6/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuufAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAOutyADrrVAA66yoAOusIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAOuu/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA6658AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA6698AOuvzADrrnQA66zYAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6678AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr
nwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrr3wA66/8AOuv/ADrr/wA669EAOusk
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrrvwA66/8AOuv/ADrr/wA66/8A
Ouv/ADrr/wA66/8AOuufAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuvfADrr/wA6
6/8AOuv/ADrr/wA660AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuu/ADrr
/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA6658AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAA6698AOuv/ADrr/wA66/8AOuv/ADrrQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA6678AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrrnwAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAADrr3wA66/8AOuv/ADrr/wA66/8AOutAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAADrrvwA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuuf
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuvfADrr/wA66/8AOuv/ADrr/wA660AA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuu/ADrr/wA66/8AOuv/ADrr/wA6
6/8AOuv/ADrr/wA6658AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6698AOuv/ADrr
/wA66/8AOuv/ADrrQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6678AOuv/
ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrrnwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAADrr3wA66/8AOuv/ADrr/wA66/8AOutAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAADrrvwA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuufAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAOuvfADrr/wA66/8AOuv/ADrr/wA660AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAOuu/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA6658A
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6698AOuv/ADrr/wA66/8AOuv/ADrrQAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6678AOuv/ADrr/wA66/8AOuv/ADrr
/wA66/8AOuv/ADrrnwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrr3wA66/8AOuv/
ADrr/wA66/8AOutAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrrvwA66/8A
Ouv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuufAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAOuvfADrr/wA66/8AOuv/ADrr/wA660AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAOuu/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA6658AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA6698AOuv/ADrr/wA66/8AOuv/ADrrQAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA6678AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrrnwAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrr3wA66/8AOuv/ADrr/wA66/8AOutAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrrvwA66/8AOuv/ADrr/wA66/8AOuv/
ADrr/wA66/8AOuufAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuvfADrr/wA66/8A
Ouv/ADrr/wA660AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuu/ADrr/wA6
6/8AOuv/ADrr/wA66/8AOuv/ADrr/wA6658AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAA6698AOuv/ADrr/wA66/8AOuv/ADrruwA6624AOuswADrrAgAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAA6678AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrrnwAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAADrrjQA66/EAOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuvxADrrtQA6
63gAOus6ADrrBgAAAAAAAAAAADrrvwA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuufAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrrCgA661oAOuu7ADrr/QA66/8AOuv/
ADrr/wA66/8AOuv/ADrr/wA66/8AOuv3ADrrvwA664MAOuvXADrr/wA66/8AOuv/ADrr/wA66/8A
Ouv/ADrr/wA6658AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAOuseADrrfAA669sAOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr
/wA66/8AOuv/ADrr/wA66/8AOuv/ADrrnwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrrAAA66zwAOuubADrr8QA66/8AOuv/ADrr/wA66/8A
Ouv/ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr/wA66/kAOut+AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOusKADrr
XAA6670AOuv9ADrr/wA66/8AOuv/ADrr/wA66/8AOuv/ADrr5wA6650AOutSADrrDgAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA66x4AOut8ADrr2wA66/0AOuvHADrrfAA66zIAOusCAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOusAADrrEAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////
////7////wD///gAH//AAA//AAAP+AHgD/D/4A/w/+AP8D/gD/A/4A/wP+AP8D/gD/A/4A/wP+AP
8D/gD/A/4A/wP+AP8D/gD/A/4A/wP+AP8D/gD/A/4A/wB+AP8ABgD/gAAA//AAAP/+AAD//4AB//
/wD////v//////8oAAAAGAAAADAAAAABACAAAAAAAGAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrrAgA660IAOuuHADrrTAA66wwAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5
6iYAOuuFADnq4QA66/8AOer/ADnq/wA66/UAOeq3ADrrbAA56iIAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA66xIAOutoADrrxwA66/8AOuv/ADnr/wA66/8AOev/
ADnr/wA66/8AOev/ADnr/wA66/8AOeqjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA66wYA
OupMADrrqwA66/EAOuvdADrruwA665cAOutyADnqUAA66ywAOuuZADrr/wA66/8AOuv/ADrr/wA6
6/8AOeq3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADnqVAA661YAOetIADrrJgA56ggAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAOuuPADnq/wA66/8AOer/ADnq/wA66/8AOeq3AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAADnq5wA669kAOut0ADnqFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
OeqPADnr/wA66/8AOev/ADnr/wA66/8AOeq3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADnr5wA6
6/8AOuv/ADnr6wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuuPADrr/wA66/8AOuv/ADrr
/wA66/8AOeq3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrr5wA56v8AOer/ADrr7wAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAOuuPADnq/wA66/8AOer/ADnq/wA66/8AOeq3AAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAADnq5wA66/8AOuv/ADrr7wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAOeqPADnr/wA66/8AOev/ADnr/wA66/8AOeq3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADnr
5wA66/8AOuv/ADnr7wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuuPADrr/wA66/8AOuv/
ADrr/wA66/8AOeq3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrr5wA56v8AOer/ADrr7wAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuuPADnq/wA66/8AOer/ADnq/wA66/8AOeq3AAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAADrq5wA66/8AOuv/ADrr7wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAOuuPADnr/wA66/8AOer/ADnr/wA66/8AOeq3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
ADnq5wA56v8AOev/ADnq7wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOeqPADnq/wA66/8A
Our/ADnq/wA66/8AOuq3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrr5wA66/8AOer/ADrr7wAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOuuPADrr/wA66/8AOer/ADrr/wA66/8AOeu3AAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAADrq5wA66/8AOuv/ADrr7wAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAOuuPADnr/wA66/8AOer/ADnr/wA66/8AOeq3AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAADnq5wA56v8AOev/ADnq7wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOeqPADnq/wA6
6/8AOur/ADnq/wA66/8AOuq3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrr5wA66/8AOer/ADrr
9wA662gAOussADrrAgAAAAAAAAAAAAAAAAAAAAAAOuuPADrr/wA66/8AOer/ADrr/wA66/8AOeu3
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrreAA5690AOur/ADnq/wA66/8AOer/ADnq7QA667EA
Oet0ADrrNgA66gYAOuuPADnr/wA66/8AOuv/ADnr/wA66/8AOeq3AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA66wIAOutAADrroQA66vMAOev/ADrr/wA66/8AOev/ADrr/wA66/MAOuvpADrr
/wA66/8AOer/ADrr/wA66/8AOeq3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAA56g4AOutgADnqwQA56v0AOuv/ADnq/wA66/8AOer/ADnq/wA66/8AOer/ADnq/wA56/8A
OeujAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6
6yIAOuuBADnr3wA66/8AOer/ADnr/wA66/UAOuu3ADrrbAA66yIAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADnqAgA660IAOeqH
ADnqTAA66gwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA////AP/wfwD/wA8A/gAHAPAABwDg/AcA4fwHAOH8BwDh/AcA4fwH
AOH8BwDh/AcA4fwHAOH8BwDh/AcA4fwHAOH8BwDgPAcA4AAHAPAABwD+AAcA/8APAP/wfwD///8A
KAAAABAAAAAgAAAAAQAgAAAAAABABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA66wQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAOusEADrrSAA666cAOuv1ADrr0QA664cAOus8ADrrBAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA66ywAOuuLADrr5wA66/kAOuvZADrr1QA66/8AOuv/ADrr/wA668cAAAAA
AAAAAAAAAAAAAAAAADrrNgA661oAOutoADrrRAA66yIAOusEAAAAAAA662AAOuv/ADrr/wA66/8A
OuvPAAAAAAAAAAAAAAAAAAAAAAA66+0AOuu1ADrrPgAAAAAAAAAAAAAAAAAAAAAAOutgADrr/wA6
6/8AOuv/ADrrzwAAAAAAAAAAAAAAAAAAAAAAOuvvADrr/wA6658AAAAAAAAAAAAAAAAAAAAAADrr
YAA66/8AOuv/ADrr/wA6688AAAAAAAAAAAAAAAAAAAAAADrr7wA66/8AOuufAAAAAAAAAAAAAAAA
AAAAAAA662AAOuv/ADrr/wA66/8AOuvPAAAAAAAAAAAAAAAAAAAAAAA66+8AOuv/ADrrnwAAAAAA
AAAAAAAAAAAAAAAAOutgADrr/wA66/8AOuv/ADrrzwAAAAAAAAAAAAAAAAAAAAAAOuvvADrr/wA6
658AAAAAAAAAAAAAAAAAAAAAADrrYAA66/8AOuv/ADrr/wA6688AAAAAAAAAAAAAAAAAAAAAADrr
7wA66/8AOuufAAAAAAAAAAAAAAAAAAAAAAA662AAOuv/ADrr/wA66/8AOuvPAAAAAAAAAAAAAAAA
AAAAAAA66+8AOuv/ADrrnwAAAAAAAAAAAAAAAAAAAAAAOutgADrr/wA66/8AOuv/ADrrzwAAAAAA
AAAAAAAAAAAAAAAAOuvvADrr/wA6678AOusoADrrAAAAAAAAAAAAADrrYAA66/8AOuv/ADrr/wA6
688AAAAAAAAAAAAAAAAAAAAAADrrYgA668UAOuv/ADrr/wA66+kAOuutADrrbgA664cAOuv/ADrr
/wA66/8AOuvPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrrJgA664UAOuvjADrr/wA66/8AOuv/
ADrr/wA66/8AOuv/ADrrxwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADrrAgA660YA
OuunADrr9QA669EAOuuHADrrPAA66wQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA66wQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/vwAA/AMAAPADAADAgwAAx4MA
AMeDAADHgwAAx4MAAMeDAADHgwAAx4MAAMODAADAAwAA8AMAAPwDAAD/vwAA')

	$tabContainer.Controls.Add($tabXml)
	$tabContainer.Controls.Add($tabQuery)
	$tabContainer.Dock = 'Fill'
	$tabContainer.Location = '0, 0'
	$tabContainer.Name = "tabContainer"
	$tabContainer.SelectedIndex = 0
	$tabContainer.Size = '884, 461'
	$tabContainer.TabIndex = 9

	$tabXml.Controls.Add($splitVertical)
	$tabXml.Controls.Add($textNodePath)
	$tabXml.Controls.Add($buttonImport)
	$tabXml.Controls.Add($textImportFile)
	$tabXml.Location = '4, 22'
	$tabXml.Name = "tabXml"
	$tabXml.Padding = '3, 3, 3, 3'
	$tabXml.Size = '876, 435'
	$tabXml.TabIndex = 1
	$tabXml.Text = "XML Browser"
	$tabXml.UseVisualStyleBackColor = $True

	$splitVertical.Anchor = 'Top, Bottom, Left, Right'
	$splitVertical.ContextMenuStrip = $menuContext
	$splitVertical.Location = '6, 35'
	$splitVertical.Name = "splitVertical"
	[void]$splitVertical.Panel1.Controls.Add($treeCollectionNodes)
	[void]$splitVertical.Panel2.Controls.Add($splitHorizontal)
	$splitVertical.Size = '864, 394'
	$splitVertical.SplitterDistance = 275
	$splitVertical.TabIndex = 3
	$splitVertical.TabStop = $False

	$textNodePath.Anchor = 'Top, Right'
	$textNodePath.Location = '670, 8'
	$textNodePath.Name = "textNodePath"
	$textNodePath.Size = '200, 20'
	$textNodePath.TabIndex = 7

	$buttonImport.Location = '6, 6'
	$buttonImport.Name = "buttonImport"
	$buttonImport.Size = '75, 23'
	$buttonImport.TabIndex = 4
	$buttonImport.Text = "Import"
	$buttonImport.UseVisualStyleBackColor = $True
	$buttonImport.add_Click($buttonImport_Click)

	$textImportFile.Location = '87, 8'
	$textImportFile.Name = "textImportFile"
	$textImportFile.Size = '577, 20'
	$textImportFile.TabIndex = 5

	$tabQuery.Controls.Add($buttonReset)
	$tabQuery.Controls.Add($checkboxSavePreferences)
	$tabQuery.Controls.Add($buttonConnect)
	$tabQuery.Controls.Add($buttonSearch)
	$tabQuery.Controls.Add($textSearch)
	$tabQuery.Controls.Add($buttonExportXML)
	$tabQuery.Controls.Add($textConnectionUrl)
	$tabQuery.Controls.Add($comboConnection)
	$tabQuery.Controls.Add($panelQueryStatus)
	$tabQuery.Controls.Add($buttonBrowseXML)
	$tabQuery.Controls.Add($buttonRefresh)
	$tabQuery.Controls.Add($comboFilter)
	$tabQuery.Controls.Add($dataMoveRequest)
	$tabQuery.Controls.Add($labelSessionStatus)
	$tabQuery.Location = '4, 22'
	$tabQuery.Name = "tabQuery"
	$tabQuery.Padding = '3, 3, 3, 3'
	$tabQuery.Size = '876, 435'
	$tabQuery.TabIndex = 0
	$tabQuery.Text = "Query Exchange"
	$tabQuery.UseVisualStyleBackColor = $True
	$tabQuery.add_Enter($tabQuery_Enter)

	$buttonReset.Anchor = 'Bottom, Left'
	$buttonReset.Location = '460, 406'
	$buttonReset.Name = "buttonReset"
	$buttonReset.Size = '75, 23'
	$buttonReset.TabIndex = 28
	$buttonReset.Text = "Reset"
	$buttonReset.UseVisualStyleBackColor = $True
	$buttonReset.add_Click($buttonReset_Click)

	$checkboxSavePreferences.Location = '559, 6'
	$checkboxSavePreferences.Name = "checkboxSavePreferences"
	$checkboxSavePreferences.Size = '126, 24'
	$checkboxSavePreferences.TabIndex = 27
	$checkboxSavePreferences.Text = "Save Preferences"
	$checkboxSavePreferences.UseVisualStyleBackColor = $True
	$checkboxSavePreferences.Visible = $False
	$checkboxSavePreferences.add_CheckedChanged($checkboxSavePreferences_CheckedChanged)

	$buttonConnect.Anchor = 'Top, Right'
	$buttonConnect.Location = '770, 6'
	$buttonConnect.Name = "buttonConnect"
	$buttonConnect.Size = '100, 23'
	$buttonConnect.TabIndex = 26
	$buttonConnect.Text = "Connect"
	$buttonConnect.UseVisualStyleBackColor = $True
	$buttonConnect.add_Click($buttonConnect_Click)

	$buttonSearch.Anchor = 'Bottom, Left'
	$buttonSearch.Location = '379, 406'
	$buttonSearch.Name = "buttonSearch"
	$buttonSearch.Size = '75, 23'
	$buttonSearch.TabIndex = 25
	$buttonSearch.Text = "Search"
	$buttonSearch.UseVisualStyleBackColor = $True
	$buttonSearch.add_Click($buttonSearch_Click)

	$textSearch.Anchor = 'Bottom, Left'
	$textSearch.Location = '231, 408'
	$textSearch.Name = "textSearch"
	$textSearch.Size = '142, 20'
	$textSearch.TabIndex = 24
	$textSearch.Text = "Name, Alias, or Batch"
	$textSearch.add_Enter($textSearch_Enter)

	$buttonExportXML.Anchor = 'Bottom, Right'
	$buttonExportXML.Enabled = $False
	$buttonExportXML.Location = '770, 406'
	$buttonExportXML.Name = "buttonExportXML"
	$buttonExportXML.Size = '100, 23'
	$buttonExportXML.TabIndex = 23
	$buttonExportXML.Text = "Export XML"
	$buttonExportXML.UseVisualStyleBackColor = $True
	$buttonExportXML.add_Click($buttonExportXML_Click)

	$textConnectionUrl.Location = '181, 8'
	$textConnectionUrl.Name = "textConnectionUrl"
	$textConnectionUrl.Size = '372, 20'
	$textConnectionUrl.TabIndex = 21
	$textConnectionUrl.Text = "https://outlook.office365.com/powershell-liveid"
	$textConnectionUrl.add_Enter($textConnectionUrl_Enter)

	$comboConnection.FormattingEnabled = $True
	[void]$comboConnection.Items.Add("Commercial Worldwide")
	[void]$comboConnection.Items.Add("Federal & Defense ITAR")
	[void]$comboConnection.Items.Add("On-Premises & Dedicated")
	[void]$comboConnection.Items.Add("Local Session")
	$comboConnection.Location = '8, 8'
	$comboConnection.Name = "comboConnection"
	$comboConnection.Size = '167, 21'
	$comboConnection.TabIndex = 20
	$comboConnection.Text = "Commercial Worldwide"
	$comboConnection.add_SelectedIndexChanged($comboConnection_SelectedIndexChanged)

	$panelQueryStatus.Controls.Add($textQueryStatus)
	$panelQueryStatus.BorderStyle = 'FixedSingle'
	$panelQueryStatus.Location = '307, 188'
	$panelQueryStatus.Name = "panelQueryStatus"
	$panelQueryStatus.Size = '246, 45'
	$panelQueryStatus.TabIndex = 19
	$panelQueryStatus.UseWaitCursor = $True
	$panelQueryStatus.Visible = $False

	$textQueryStatus.BorderStyle = 'None'
	$textQueryStatus.Font = "Microsoft Sans Serif, 14.25pt"
	$textQueryStatus.Location = '3, 9'
	$textQueryStatus.Multiline = $True
	$textQueryStatus.Name = "textQueryStatus"
	$textQueryStatus.Size = '238, 25'
	$textQueryStatus.TabIndex = 0
	$textQueryStatus.Text = "Retrieving data..."
	$textQueryStatus.TextAlign = 'Center'
	$textQueryStatus.UseWaitCursor = $True

	$buttonBrowseXML.Anchor = 'Bottom, Right'
	$buttonBrowseXML.Enabled = $False
	$buttonBrowseXML.Location = '664, 406'
	$buttonBrowseXML.Name = "buttonBrowseXML"
	$buttonBrowseXML.Size = '100, 23'
	$buttonBrowseXML.TabIndex = 18
	$buttonBrowseXML.Text = "Browse XML"
	$buttonBrowseXML.UseVisualStyleBackColor = $True
	$buttonBrowseXML.add_Click($buttonBrowseXML_Click)

	$buttonRefresh.Anchor = 'Bottom, Left'
	$buttonRefresh.Location = '8, 406'
	$buttonRefresh.Name = "buttonRefresh"
	$buttonRefresh.Size = '75, 23'
	$buttonRefresh.TabIndex = 16
	$buttonRefresh.Text = "Refresh"
	$buttonRefresh.UseVisualStyleBackColor = $True
	$buttonRefresh.add_Click($buttonRefresh_Click)

	$comboFilter.Anchor = 'Bottom, Left'
	$comboFilter.FormattingEnabled = $True
	[void]$comboFilter.Items.Add("All")
	[void]$comboFilter.Items.Add("AutoSuspended")
	[void]$comboFilter.Items.Add("Completed")
	[void]$comboFilter.Items.Add("CompletedWithWarning")
	[void]$comboFilter.Items.Add("CompletionInProgress")
	[void]$comboFilter.Items.Add("Failed")
	[void]$comboFilter.Items.Add("InProgress")
	[void]$comboFilter.Items.Add("Queued")
	[void]$comboFilter.Items.Add("Synced")
	[void]$comboFilter.Items.Add("Suspended")
	$comboFilter.Location = '89, 408'
	$comboFilter.Name = "comboFilter"
	$comboFilter.Size = '136, 21'
	$comboFilter.TabIndex = 15
	$comboFilter.Text = "All"
	$comboFilter.add_SelectedIndexChanged($comboFilter_SelectedIndexChanged)

	$dataMoveRequest.AllowUserToAddRows = $False
	$dataMoveRequest.AllowUserToDeleteRows = $False
	$dataMoveRequest.AllowUserToOrderColumns = $True
	$dataMoveRequest.AllowUserToResizeRows = $False
	$dataMoveRequest.Anchor = 'Top, Bottom, Left, Right'
	$dataMoveRequest.AutoSizeColumnsMode = 'AllCells'
	$dataMoveRequest.BackgroundColor = 'Window'
	$dataMoveRequest.BorderStyle = 'Fixed3D'
	$dataMoveRequest.ColumnHeadersHeightSizeMode = 'AutoSize'
	$dataMoveRequest.GridColor = 'Window'
	$dataMoveRequest.Location = '8, 35'
	$dataMoveRequest.MultiSelect = $False
	$dataMoveRequest.Name = "dataMoveRequest"
	$dataMoveRequest.ReadOnly = $True
	$dataMoveRequest.RowHeadersVisible = $False
	$dataMoveRequest.SelectionMode = 'FullRowSelect'
	$dataMoveRequest.Size = '862, 365'
	$dataMoveRequest.TabIndex = 14
	$dataMoveRequest.add_DoubleClick($dataMoveRequest_DoubleClick)

	$labelSessionStatus.Anchor = 'Top, Right'
	$labelSessionStatus.BackColor = 'Red'
	$labelSessionStatus.Font = "Microsoft Sans Serif, 8.25pt"
	$labelSessionStatus.ForeColor = 'White'
	$labelSessionStatus.Location = '691, 6'
	$labelSessionStatus.Name = "labelSessionStatus"
	$labelSessionStatus.Size = '73, 23'
	$labelSessionStatus.TabIndex = 12
	$labelSessionStatus.Text = "Offline"
	$labelSessionStatus.TextAlign = 'MiddleCenter'

	$treeCollectionNodes.Dock = 'Fill'
	$treeCollectionNodes.HideSelection = $False
	$treeCollectionNodes.Location = '0, 0'
	$treeCollectionNodes.Name = "treeCollectionNodes"
	$treeCollectionNodes.Size = '275, 394'
	$treeCollectionNodes.TabIndex = 0
	$treeCollectionNodes.add_AfterSelect($treeCollectionNodes_AfterSelect)

	$listCollectionEntries.ContextMenuStrip = $menuContext
	$listCollectionEntries.Dock = 'Fill'
	$listCollectionEntries.FormattingEnabled = $True
	$listCollectionEntries.HorizontalScrollbar = $True
	$listCollectionEntries.Location = '0, 0'
	$listCollectionEntries.Name = "listCollectionEntries"
	$listCollectionEntries.ScrollAlwaysVisible = $True
	$listCollectionEntries.Size = '585, 194'
	$listCollectionEntries.TabIndex = 0
	$listCollectionEntries.add_SelectedIndexChanged($listCollectionEntries_SelectedIndexChanged)

	$fileOpenDialog.FileName = "openfiledialog1"
	$fileSaveDialog.DefaultExt = "xml"

	[void]$menuContext.Items.Add($menuContextCopy)
	$menuContext.Name = "contextmenustrip1"
	$menuContext.ShowImageMargin = $False
	$menuContext.Size = '36, 4'

	$menuContextCopy.Name = "menuContextCopy"
	$menuContextCopy.Size = '148, 22'
	$menuContextCopy.Text = "Copy To Clipboard"
	$menuContextCopy.add_Click($menuContextCopy_Click)

	$textEntryDetails.BackColor = 'Window'
	$textEntryDetails.Dock = 'Fill'
	$textEntryDetails.Font = "Consolas, 8.25pt"
	$textEntryDetails.Location = '0, 0'
	$textEntryDetails.Multiline = $True
	$textEntryDetails.Name = "textEntryDetails"
	$textEntryDetails.ReadOnly = $True
	$textEntryDetails.ScrollBars = 'Both'
	$textEntryDetails.Size = '585, 196'
	$textEntryDetails.TabIndex = 2
	$textEntryDetails.WordWrap = $False

	$splitHorizontal.Dock = 'Fill'
	$splitHorizontal.Location = '0, 0'
	$splitHorizontal.Name = "splitHorizontal"
	$splitHorizontal.Orientation = 'Horizontal'
	[void]$splitHorizontal.Panel1.Controls.Add($listCollectionEntries)
	[void]$splitHorizontal.Panel2.Controls.Add($textEntryDetails)
	$splitHorizontal.Size = '585, 394'
	$splitHorizontal.SplitterDistance = 194
	$splitHorizontal.TabIndex = 3

	$InitialFormWindowState = $formMRSExplorer.WindowState
	$formMRSExplorer.add_Load($Form_StateCorrection_Load)
	$formMRSExplorer.add_FormClosed($Form_Cleanup_FormClosed)
	return $formMRSExplorer.ShowDialog()

}

If ((OnApplicationLoad) -eq $true) {
    cls; Write-Host $ScriptInfo
	Call-MRS_Explorer | Out-Null
	OnApplicationExit
}
